[build]
#set default target
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[dependencies]
ADB = { git = "https://github.com/ImKKingshuk/Rust-ADB.git" }
