name: Build aa-mirror-rs
run-name: Build aa-mirror-rs:${{github.event.head_commit.message}}
on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:
    inputs:
      buildLevel:
        description: 'Build level'
        required: true
        default: 'debug'
        type: choice
        options:
        - release
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64-unknown-linux-gnu]
    steps:
    - uses: actions/checkout@v4
    - name: Install aarch64 Rust target and cross toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libc6-dev-arm64-cross
        rustup target add aarch64-unknown-linux-gnu
        
    - name: Build Debug
      if: ${{ github.event.inputs.buildLevel == 'debug' }}
      run: cargo build --verbose --target aarch64-unknown-linux-gnu
    - name: Build Release
      if: ${{ github.event.inputs.buildLevel == 'release' }}
      run: cargo build --release --verbose --target ${{ matrix.target }}
    - uses: actions/upload-artifact@v4
      with:
        name: aa-mirror-rs-${{ github.event.inputs.buildLevel }}
        path: ~/work/aa-mirror-rs/aa-mirror-rs/target/${{ matrix.target }}/${{ github.event.inputs.buildLevel }}/aa-mirror-rs
    - name: Get commit message
      id: commit
      run: |
        echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
    - name: my package:${{ steps.commit.outputs.msg }}
      run: echo "Building"
    #- name: Run tests
      #run: cargo test --verbose --target aarch64-unknown-linux-gnu
